ECHO OFF
SET TODAY_FOLDER=\\MINSMCHIEN-3020\report\json\%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%

SET CURRENT_TIME=%DATE:~0,10% %TIME% 
SET SN=MA3XXXXXXXXX
SET SN=MA3YYYYYYYYY
SET VER=V1.085
SET RESULT=PASS
SET EVENT_COUNT=500000
SET EVENT_DELAY=200
SET MTTF=27.78
SET DROP_COUNT=123456
SET DROP_RATE=2.78
SET TOTAL_TIME=633.487

ECHO CREATE FOLDER %TODAY_FOLDER%
MKDIR %TODAY_FOLDER%
REM CD %TODAY_FOLDER%
CALL:CREATE_JSON_REPORT

REM END OF BATCH
GOTO:EOF


REM========================================================================

:CREATE_JSON_REPORT
ECHO {"CURRENT_TIME":"%CURRENT_TIME%","SN":"%SN%","VER":"%VER%","RESULT":"%RESULT%","EVENT_COUNT":"%EVENT_COUNT%","EVENT_DELAY":"%EVENT_DELAY%","MTTF":"%MTTF%","DROP_COUNT":"%DROP_COUNT%","DROP_RATE":"%DROP_RATE%","START_TIME":"%START_TIME%","STOP_TIME":"%STOP_TIME%","TOTAL_TIME":"%TOTAL_TIME%"} > %TODAY_FOLDER%\%SN%.json
GOTO:EOF